### ISSUE TITLE
Add CLI options

### ISSUE THREAD

**Issue by wmodes** [ataylorme/pantheon-bulks-site-create-clone#10]
Andrew, thanks for your work on this script.

Please add command line options to the script to optionally automate the dialogue.

Given that [issue 8](https://github.com/ataylorme/pantheon-bulks-site-create-clone/issues/8) requires one to rerun the script dozens of times, having the CLI options to bypass the dialogue would have been great.

I'm not sure you want to laboriously adapt a bash script or rewrite it in python or something.

Wes

**Comment by ataylorme** [comment]
> Please add command line options to the script to optionally automate the dialogue.

@wmodes This script was written to serve my needs. I shared it hoping others could benefit from it or use it as an example. I plan to test #8 when I have the bandwidth. However, I don't have plans to remove the prompts.

Feel free to fork/download the script and modify it to fit your needs. For example, you can remove the prompts and hard code `PROJECT_SLUG`,  `SOURCE_UUID`, etc. in your copy if that is better for your workflow.
