### ISSUE TITLE
Create an org

### ISSUE THREAD

**Issue by davidneedham** [ataylorme/pantheon-bulks-site-create-clone#4]
I don't see a relevant Terminus command, but is there a way to add a step in the script for adding an org based on the project name? It would be really useful if the script was able to spin up a new org for each class so that we don't have to go in and manually set it up each time.

Desired behavior: if you don't provide an org UUID, it creates one for you from the slug/project name already defined.

**Comment by ataylorme** [comment]
This isn't possible as there is not a programmatic way to create an organization.
